import "./globals.css";
import type { Metadata } from "next";
import { poppins } from "../lib/font";
import { ChildElement } from "../lib/type-definations";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildElement) {
  return (
    <html lang="en" className="h-[100vh] w-[100vw] overflow-hidden">
      <body
        className={`bg-gray h-full w-full overflow-hidden antialiased ${poppins.variable}`}
      >
        <Navbar />
        <main>
          <div className="flex h-[89vh] overflow-hidden">
            <Sidebar />
            <div className="scroll-y-auto w-full px-6 py-10">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
