import "./globals.css";
import type { Metadata } from "next";
import { geistMono, geistSans } from "../lib/font";
import { ChildElement } from "../lib/type-definations";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import DashboardHero from "../components/DashboardHero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildElement) {
  return (
    <html lang="en" className="h-[100vh] w-[100vw] overflow-hidden">
      <body
        className={`bg-gray h-full w-full overflow-x-hidden antialiased ${geistSans.variable} ${geistMono.variable}`}
      >
        <Navbar />
        <main>
          <div>
            <Sidebar />
            <div>
              <DashboardHero />
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
